### ISSUE TITLE
Will there be any continuation on the blog tutorial ?

### ISSUE THREAD

**Issue by sadhakbj** [stefanbauer/pingping#4]

**Comment by stefanbauer** [comment]
Thanks for getting in touch.

I am not sure, to be honest. The project itself has quite finished already. But writing that always down is a lot of work for me as English is not my native language. I have more than 1000 subscribers on that list, but the most people are just trying to get as much free content as possible. So already the first copies in the web. So what I'm gonna to do, that I will just show the most important steps and ideas in the future instead of showing every single step.
